import { useAppTranslation } from "config.js";
import useCountries from "hooks/useCountries";

const useWorldCountries = () => {
  const { trans: t } = useAppTranslation();
  const { countriesMiddleEast } = useCountries();

  // code is usded for functionalitiy
  // while name is used for the user trnasation
  const otherCountries = [
    // Europe
    {
      id: "uk",
      code: "United Kingdom",
      name: t("countries:unitedKingdom.name"),
      phoneCode: "+44",
      mobileLength: "10",
      coordinates: [-1, 51],
    },
    {
      id: "fr",
      code: "France",
      name: t("countries:france.name"),
      phoneCode: "+33",
      mobileLength: "9",
      coordinates: [2, 46],
    },
    {
      id: "de",
      code: "Germany",
      name: t("countries:germany.name"),
      phoneCode: "+49",
      mobileLength: "10",
      coordinates: [10, 51],
    },
    {
      id: "it",
      code: "Italy",
      name: t("countries:italy.name"),
      phoneCode: "+39",
      mobileLength: "10",
      coordinates: [12, 43],
    },
    {
      id: "es",
      code: "Spain",
      name: t("countries:spain.name"),
      phoneCode: "+34",
      mobileLength: "9",
      coordinates: [-3, 40],
    },
    {
      id: "nl",
      code: "Netherlands",
      name: t("countries:netherlands.name"),
      phoneCode: "+31",
      mobileLength: "9",
      coordinates: [5, 52],
    },
    {
      id: "se",
      code: "Sweden",
      name: t("countries:sweden.name"),
      phoneCode: "+46",
      mobileLength: "9",
      coordinates: [15, 62],
    },
    {
      id: "no",
      code: "Norway",
      name: t("countries:norway.name"),
      phoneCode: "+47",
      mobileLength: "8",
      coordinates: [10, 61],
    },
    {
      id: "ru",
      code: "Russia",
      name: t("countries:russia.name"),
      phoneCode: "+7",
      mobileLength: "10",
      coordinates: [100, 60],
    },
    // Americas
    {
      id: "us",
      code: "United States",
      name: t("countries:unitedStates.name"),
      phoneCode: "+1",
      mobileLength: "10",
      coordinates: [-100, 40],
    },
    {
      id: "ca",
      code: "Canada",
      name: t("countries:canada.name"),
      phoneCode: "+1",
      mobileLength: "10",
      coordinates: [-106, 56],
    },
    {
      id: "mx",
      code: "Mexico",
      name: t("countries:mexico.name"),
      phoneCode: "+52",
      mobileLength: "10",
      coordinates: [-102, 23],
    },
    {
      id: "br",
      code: "Brazil",
      name: t("countries:brazil.name"),
      phoneCode: "+55",
      mobileLength: "11",
      coordinates: [-53, -10],
    },
    {
      id: "ar",
      code: "Argentina",
      name: t("countries:argentina.name"),
      phoneCode: "+54",
      mobileLength: "10",
      coordinates: [-64, -34],
    },
    {
      id: "cl",
      code: "Chile",
      name: t("countries:chile.name"),
      phoneCode: "+56",
      mobileLength: "9",
      coordinates: [-71, -33],
    },
    // Asia
    {
      id: "cn",
      code: "China",
      name: t("countries:china.name"),
      phoneCode: "+86",
      mobileLength: "11",
      coordinates: [103, 35],
    },
    {
      id: "jp",
      code: "Japan",
      name: t("countries:japan.name"),
      phoneCode: "+81",
      mobileLength: "10",
      coordinates: [138, 36],
    },
    {
      id: "in",
      code: "India",
      name: t("countries:india.name"),
      phoneCode: "+91",
      mobileLength: "10",
      coordinates: [78, 20],
    },
    {
      id: "kr",
      code: "South Korea",
      name: t("countries:southKorea.name"),
      phoneCode: "+82",
      mobileLength: "10",
      coordinates: [127, 37],
    },
    {
      id: "id",
      code: "Indonesia",
      name: t("countries:indonesia.name"),
      phoneCode: "+62",
      mobileLength: "10",
      coordinates: [106, -6],
    },
    // Africa
    {
      id: "ng",
      code: "Nigeria",
      name: t("countries:nigeria.name"),
      phoneCode: "+234",
      mobileLength: "10",
      coordinates: [8, 10],
    },
    {
      id: "za",
      code: "South Africa",
      name: t("countries:southAfrica.name"),
      phoneCode: "+27",
      mobileLength: "9",
      coordinates: [24, -29],
    },
    {
      id: "ke",
      code: "Kenya",
      name: t("countries:kenya.name"),
      phoneCode: "+254",
      mobileLength: "9",
      coordinates: [37, 1],
    },
    // Oceania
    {
      id: "au",
      code: "Australia",
      name: t("countries:australia.name"),
      phoneCode: "+61",
      mobileLength: "9",
      coordinates: [133, -25],
    },
    {
      id: "nz",
      code: "New Zealand",
      name: t("countries:newZealand.name"),
      phoneCode: "+64",
      mobileLength: "8",
      coordinates: [174, -41],
    },

    // Europe (cont.)
    {
      id: "gr",
      code: "Greece",
      name: t("countries:greece.name"),
      phoneCode: "+30",
      mobileLength: "10",
      coordinates: [21.8243, 39.0742],
    },
    {
      id: "ch",
      code: "Switzerland",
      name: t("countries:switzerland.name"),
      phoneCode: "+41",
      mobileLength: "9",
      coordinates: [8.2275, 46.8182],
    },
    {
      id: "at",
      code: "Austria",
      name: t("countries:austria.name"),
      phoneCode: "+43",
      mobileLength: "9",
      coordinates: [13.3333, 47.3333],
    },
    {
      id: "be",
      code: "Belgium",
      name: t("countries:belgium.name"),
      phoneCode: "+32",
      mobileLength: "9",
      coordinates: [4.4699, 50.5039],
    },
    {
      id: "dk",
      code: "Denmark",
      name: t("countries:denmark.name"),
      phoneCode: "+45",
      mobileLength: "8",
      coordinates: [9.5018, 56.2639],
    },
    {
      id: "fi",
      code: "Finland",
      name: t("countries:finland.name"),
      phoneCode: "+358",
      mobileLength: "10",
      coordinates: [25.7482, 61.9241],
    },
    {
      id: "pt",
      code: "Portugal",
      name: t("countries:portugal.name"),
      phoneCode: "+351",
      mobileLength: "9",
      coordinates: [-8.2245, 39.3999],
    },

    // Africa (cont.)
    {
      id: "ma",
      code: "Morocco",
      name: t("countries:morocco.name"),
      phoneCode: "+212",
      mobileLength: "9",
      coordinates: [-7.0926, 31.7917],
    },
    {
      id: "dz",
      code: "Algeria",
      name: t("countries:algeria.name"),
      phoneCode: "+213",
      mobileLength: "9",
      coordinates: [1.6596, 28.0339],
    },
    {
      id: "tn",
      code: "Tunisia",
      name: t("countries:tunisia.name"),
      phoneCode: "+216",
      mobileLength: "8",
      coordinates: [9.5375, 33.8869],
    },
    {
      id: "et",
      code: "Ethiopia",
      name: t("countries:ethiopia.name"),
      phoneCode: "+251",
      mobileLength: "9",
      coordinates: [39.6012, 9.145],
    },
    {
      id: "gh",
      code: "Ghana",
      name: t("countries:ghana.name"),
      phoneCode: "+233",
      mobileLength: "9",
      coordinates: [-1.0232, 7.9465],
    },

    // Asia (cont.)
    {
      id: "th",
      code: "Thailand",
      name: t("countries:thailand.name"),
      phoneCode: "+66",
      mobileLength: "9",
      coordinates: [100.9925, 15.87],
    },
    {
      id: "my",
      code: "Malaysia",
      name: t("countries:malaysia.name"),
      phoneCode: "+60",
      mobileLength: "9",
      coordinates: [101.9758, 4.2105],
    },
    {
      id: "sg",
      code: "Singapore",
      name: t("countries:singapore.name"),
      phoneCode: "+65",
      mobileLength: "8",
      coordinates: [103.8198, 1.3521],
    },
    {
      id: "ph",
      code: "Philippines",
      name: t("countries:philippines.name"),
      phoneCode: "+63",
      mobileLength: "10",
      coordinates: [121.774, 12.8797],
    },
    {
      id: "vn",
      code: "Vietnam",
      name: t("countries:vietnam.name"),
      phoneCode: "+84",
      mobileLength: "9",
      coordinates: [108.2772, 14.0583],
    },

    // Oceania (cont.)
    {
      id: "fj",
      code: "Fiji",
      name: t("countries:fiji.name"),
      phoneCode: "+679",
      mobileLength: "7",
      coordinates: [179.4144, -17.7134],
    },
    {
      id: "pg",
      code: "Papua New Guinea",
      name: t("countries:papuaNewGuinea.name"),
      phoneCode: "+675",
      mobileLength: "8",
      coordinates: [143.9555, -6.3149],
    },
  ];

  const allCountries = [...countriesMiddleEast, ...otherCountries];

  return allCountries;
};

export default useWorldCountries;
