export const hardcodedSuggestionsFilter = [
  "food",
  "phone",
  "iphone",
  "pharmaceutical",
  "garment",
  "chemical",
  "automotive",
  "engineering",
  "materials",
  "building",
  "agricultural",
  "medical",
  "electronic",
  "game",
  "household",
  "home",
  "electronics",
  "computers",
  "computer",
  "smartphones",
  "gadgets",
  "audio",
  "headphones",
  "cameras",
  "photography",
  "clothing",
  "fashion",
  "men",
  "women",
  "shoes",
  "accessories",
  "jewelry",
  "watches",
  "home",
  "living",
  "furniture",
  "home decor",
  "kitchen",
  "dining",
  "bedding",
  "bath",
  "beauty",
  "personal",
  "care",
  "skincare",
  "makeup",
  "haircare",
  "fragrances",
  "books",
  "movies",
  "music",
  "tv",
  "shows",
  "sports",
  "outdoors",
  "outdoor",
  "recreation",
  "equipment",
  "activewear",
  "toys",
  "games",
  "kids",
  "board",
  "puzzles",
  "automotive",
  "car",
  "accessories",
  "tools",
  "equipment",
  "motorcycle",
  "health",
  "wellness",
  "vitamins",
  "supplements",
  "fitness",
  "equipment",
  "personal",
  "care",
  "office",
  "stationery",
  "office supplies",
  "stationery",
  "printers",
  "ink",

  "travel",
  "vacation",
  "tourism",
  "hotels",
  "destinations",
  "finance",
  "banking",
  "investment",
  "credit",
  "insurance",
  "education",
  "university",
  "courses",
  "learning",
  "books",
  "technology",
  "software",
  "hardware",
  "programming",
  "apps",
  "music",
  "instruments",
  "concerts",
  "festivals",
  "albums",
  "art",
  "painting",
  "sculpture",
  "photography",
  "gallery",
  "pets",
  "dogs",
  "cats",
  "pet care",
  "pet food",
  "gardening",
  "plants",
  "flowers",
  "landscaping",
  "gardening tools",
  "cooking",
  "recipes",
  "food blogs",
  "kitchen gadgets",
  "cooking utensils",
  "celebrities",
  "movies",
  "TV shows",
  "gossip",
  "entertainment",
  "science",
  "research",
  "innovation",
  "technology",
  "discovery",
  "history",
  "ancient civilizations",
  "historical events",
  "museums",
  "archives",
  "DIY",
  "crafts",
  "home projects",
  "handmade",
  "DIY tools",
  "environment",
  "sustainability",
  "green living",
  "climate change",
  "renewable energy",
  "fishing",
  "angling",
  "outdoor activities",
  "fishing gear",
  "boats",
  "fitness",
  "exercise",
  "workouts",
  "nutrition",
  "healthy living",
  "cycling",
  "biking",
  "bicycles",
  "cycling gear",
  "bike trails",
  "gaming",
  "video games",
  "board games",
  "gaming consoles",
  "eSports",
  "architecture",
  "design",
  "urban planning",
  "buildings",
  "architectural styles",
  "language",
  "linguistics",
  "language learning",
  "translation",
  "foreign languages",
];
